### ISSUE TITLE
To add variable with lists of mentiones

### ISSUE THREAD

**Issue by OlegDav** [jun3453/slack-pr-open-notification-action#13]
Hi @jun3453 
I like the idea of mention @here in slack channel notification, but sometimes it doesn't fit for me...
I'd like to list persons to be tagged into a separate variable like "@OlegDav, @jun3453, @some-group".
Can you add this feature?
Thanks!

**Comment by jun3453** [comment]
Hi @OlegDav 
I think the idea is very good!
Please note that it is necessary to specify the UserID due to the specifications of Slack.

For example, I'm thinking of adding the following options 
`IS_SEND_MENTION_USERS = [1234, 5678, 8900]`

It's not difficult, so I'll implement it when I have time.

**Comment by OlegDav** [comment]
Thank you very much!
 I'd like to add also group of users like @android-devs. I'm not sure, hope
that groups also have their ID to be listed in parameter
IS_SEND_MENTION_USERS = [1234, 5678, 8900, <groupID>]
Have a nice day!
Oleg



ср, 15 сент. 2021 г., 04:58 junki ***@***.***>:

**Comment by jun3453** [comment]
@OlegDav 
Sorry I made you wait.
Released in v1.3.0!

**Comment by OlegDav** [comment]
Oh, thanks!
Let me test it :-)

вт, 5 окт. 2021 г., 07:13 junki ***@***.***>:
