### ISSUE TITLE
SEND_USER_ID_MENTIONS : works only the first Slack ID from the list 

### ISSUE THREAD

**Issue by OlegDav** [jun3453/slack-pr-open-notification-action#16]
Hello @jun3453!
We are using this version 1.3.0 thank you for updating it!
I see there is a little bug in the user mentioning:
my YML contains the text:
...
IS_SEND_HERE_MENTION : true
...
SEND_USER_ID_MENTIONS : U02F1PXR76Z, U02CQ2V837H, U02CQ2V3YSK, U0166R8J010
-----
and below is the appropriate notification text:
----
**[XS-998] Create spending account for new user** #721 from **develop** to **xs-998-create-spending-account-for-new-user-fix**.@here@OlegNik <@ U02CQ2V837H> <@ U02CQ2V3YSK> <@ U0166R8J010>
---
It seems that only first SlackID from the list is working.
Would you like to fix it?
Thank you in advance!
Oleg

**Comment by jun3453** [comment]
@OlegDav 
Thank you for using it!

Probably the cause is that there is a space next to the comma.
Can you try to get rid of the space?

ex:
`SEND_USER_ID_MENTIONS : U02F1PXR76Z,U02CQ2V837H,U02CQ2V3YSK,U0166R8J010`
