### ISSUE TITLE
IS_SEND_HERE_MENTION : false not respected

### ISSUE THREAD

**Issue by aryzing** [jun3453/slack-pr-open-notification-action#2]
I've set up a pipeline using the settings that are recommended on the readme: I just copy pasted the whole thing and changed the mention settings to

```
IS_SEND_HERE_MENTION : false
```

However, in Slack we're still getting `@here` mentions.

**Comment by jun3453** [comment]
Thank you for using it and reporting the issue!
I think I could have fixed it.
We have released v1.0.2, so please use this.
https://github.com/jun3453/slack-pr-open-notification-action/releases/tag/v1.0.2
